**************************************
*      Model Generated by MODPEX     *
*Copyright(c) Symmetry Design Systems*
*         All Rights Reserved        *
*    UNPUBLISHED LICENSED SOFTWARE   *
*   Contains Proprietary Information *
*      Which is The Property of      *
*     SYMMETRY OR ITS LICENSORS      *
*    Modeling services provided by   *
* Interface Technologies www.i-t.com *
**************************************
.MODEL Qmje350 pnp
+IS=6.01619e-15 BF=157.387 NF=0.910131 VAF=23.273
+IKF=0.0564808 ISE=4.48479e-12 NE=1.58557 BR=0.1
+NR=1.03823 VAR=4.14543 IKR=0.0999978 ISC=1.00199e-13
+NC=1.98851 RB=0.1 IRB=0.202965 RBM=0.1
+RE=0.0710678 RC=0.355339 XTB=1.03638 XTI=3.8424
+EG=1.206 CJE=1e-11 VJE=0.75 MJE=0.33
+TF=1e-09 XTF=1 VTF=10 ITF=0.01
+CJC=1e-11 VJC=0.75 MJC=0.33 XCJC=0.9
+FC=0.5 CJS=0 VJS=0.75 MJS=0.5
+TR=1e-07 PTF=0 KF=0 AF=1
* Model generated on Feb 15, 2004
* Model format: PSpice
